<?php
$typeArr[1] = '关于我们';
$typeArr[2] = '课程体系';
$typeArr[3] = '最新资讯';
$typeArr[4] = '参与报名';
$typeArr[5] = '家长信箱';
$typeArr[6] = '联系我们';
$typeArr[7] = '夏令营简介';
$typeArr[8] = '师资优势';
$typeArr[9] = '后勤保障';
$typeArr[10] = '营地环境';
$typeArr[11] = '联系我们';
$typeArr[12] = '七天体验营';
$typeArr[13] = '十二天集训营';
$typeArr[14] = '二十天强化营';
$typeArr[15] = '二十八天特训营';
$typeArr[16] = '九天航天军事营';
$typeArr[17] = '夏令营动态';
$typeArr[18] = '夏令营活动';
$typeArr[19] = '报名须知';
$typeArr[20] = '在线报名';
?>