<li class="CON--top-rs"> 
					<dt class="fl" style="width:120px;"> 
					    <a href="[field:arcurl/]" title="[field:title/]">
                        <img src="[field:picname/]" alt="[field:title/]" title="[field:title/]" width="120" height="80"/></a>
					</dt>
					<dd class="fr" style="width:175px;">
						<h2 style="width:175px;">
							<a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a>
						</h2>
						<p style="height:45px;">[field:description function="cn_substr(@me,40)"/]...
							<a href="[field:arcurl/]" title="[field:description function="cn_substr(@me,40)"/]...">【详情】</a>
						</p>
					</dd>
					<div class="clear"></div>										 
				</li>