<?php
$z[0]=Array("field","",88,116);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",126,155);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",198,227);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n				 		<dd>\r\n				 		<a href='[field:typelink/]' title='[field:typename/]' >夏令营简介</a>\r\n				 		</dd>\r\n                        ",284,480);
$z[3][4]=array();
$z[3][4]['row']="5";

?>