<li class="nav-line"></li>		 		
		 		<li id='nav_4' style='width:133px;' >
			 		<a href='[field:typelink/]'  title='[field:typename/]' class='hover-none nav'>
			 			<span>[field:typename/]</span>
			 		</a>
			 		<dl>
				 		<dd>
				 		<a href='../message/message.html' title='提交留言' >提交留言</a>
				 		</dd>
				 		<dd>
				 		<a href='../message/' title='查看留言' >查看留言</a>
				 		</dd>
			 		</dl>
		 		</li>