
<field:kcxz itemname="课程选择" autofield="1" type="select" isnull="true" default="七天训练营,十二天集训营,二十天强化营,二十八天特训营,九天航天军事营"  maxlength="250" page="">
</field:kcxz>

<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:sex itemname="性别" autofield="1" type="select" isnull="true" default="男,女,人妖"  maxlength="250" page="">
</field:sex>

<field:minzu itemname="民族" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:minzu>

<field:csrq itemname="出身日期" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:csrq>

<field:jg itemname="籍贯" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:jg>


<field:sg itemname="身高" autofield="1" type="float" isnull="true" default=""  maxlength="250" page="">
</field:sg>

<field:xqah itemname="兴趣爱好" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:xqah>

<field:grzc itemname="个人专长" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:grzc>

<field:jzwt itemname="家长最希望解决或纠正的问题" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:jzwt>

<field:qtwt itemname="其它问题" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:qtwt>

<field:jhrxm itemname="监护人姓名  " autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:jhrxm>
