
<field:kcxz itemname="课程选择" autofield="1" type="select" isnull="true" default="七天训练营,十二天集训营,二十天强化营,二十八天特训营,九天航天军事营"  maxlength="250" page="">
</field:kcxz>

<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:sex itemname="性别" autofield="1" type="select" isnull="true" default="男,女,人妖"  maxlength="250" page="">
</field:sex>

<field:minzu itemname="民族" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:minzu>

<field:csrq itemname="出身日期" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:csrq>
