<?php
$z[0]=Array("channel","\r\n			<a href='[field:typelink/]'  title='[field:typename/]'>[field:typename/]</a>\r\n			<span>　|　</span>\r\n			",71,235);
$z[0][4]=array();
$z[0][4]['type']="son";
$z[0][4]['typeid']="1";
$z[1]=Array("global","",438,470);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",835,867);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";

?>